# Generated by Django 5.1.4 on 2024-12-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employer',
        ),
    ]
